### ISSUE TITLE
Some routing not updated when opening a preset

### ISSUE THREAD

**Issue by patmalcolm91** [fulup-bzh/AlsaJsonGateway#1]
First off, thanks for creating this software! I'm not sure if the problem I'm having is with my setup or if it's a bug.

I'm having an issue where after I start up a session and choose a preset in the HTML5 interface, I have to toggle some of the routing selections to something else and then back in order to make it work. For example, If Capture 1 is set to "Analog 1" in the preset, and I try to record from Capture 1, nothing will come through until I toggle Capture 1 to "Off" (or another selection) and then back to "Analog 1". This happens with some volume controls, input selections, capture selections, master playback route selections, and potentially other controls.

The interface I'm using is the 18i8. My machine is running Ubuntu Studio 14.10 with all up-to-date software. I installed the 4.0 realtime linux kernel to get the improved support for the interface. I'm happy to provide any other information that might.

**Comment by fulup-bzh** [comment]
Thank you for the feed back, I think you found a bug :)

I built the code in such a way that HTML5 only send a command its Internal status has changed. Normally the initial status should be provided by the driver at init time but it looks like I have some issue on this optimization. 

I will try to remove this caching optimization, if it does not impact user experience this could be an easy fix.

**Comment by fulup-bzh** [comment]
Sorry for closing the issue as quicky. I did not expect GIT to close it automatically as soon as I published a patch about it.  Hopefully updating your "AlsaJsonMixer" repository and not AlsaJsonGateway should fix your problem.

Note: as this bug is not related to AlsaJsonGateway  but to AlsaJsonMixer. If my fix does not work. I would be please you to create a new bug at AlsaJsonMixer.

Thank you
